# -*- coding: utf-8 -*-
"""A_53_ML_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ydi8ENdawrFmQIHl2JbNeMSUQP1S7keh

### ML Practical - 03

<br>

### Name: Prathamesh Rajbhoj
### Roll: A 53

<br>

#### AIM: To implement Linear regression algorithm on given dataset of height and weight and print regression coefficient and regression line.
<br>
<br>
<br>
"""

x = [5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8]
y = [53, 55, 59, 61, 65, 68, 70, 74, 76]

mean_x = sum(x)/len(x)
mean_y = sum(y)/len(y)

print("average x : ", mean_x)
print("average y : ", mean_y)

num1 = 0
num2 = 0
num = 0
den = 0

for i in range(len(x)):

  # num1 = num1 + (x[i]-mean_x)
  # num2 = num2 + (y[i]-mean_y)

  num = num + ((x[i]-mean_x)*(y[i]-mean_y))

  den = den + ((x[i]-mean_x)*(x[i]-mean_x))


# w1 = (num1*num2)/den
w1 = num/den
w0 = mean_y - w1*mean_x


print("w0 : ", w0)
print("w1 : ", w1)

print("final equation: y = ({0} x) + ({1})".format(w1, w0))

# for x = 5.9
input_height = 5.9
print('weight for 5.9 : ', (w1*5.9 + w0))

