# -*- coding: utf-8 -*-
"""A_53_ML_Prac1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ulYL09OeJe3RjMxszIw4lWkZz3eZ1cb

# Name : Prathamesh Rajbhoj
# Roll no : A-53
# Batch : A2
# Practical 1
"""

from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd
import numpy as np

data = pd.read_csv('/content/gdrive/MyDrive/enjoysport.csv')

data

data.head()

data.keys()

print(data.loc[0])

cols = len(data.keys()) - 1
cols

rows = len(data)
rows

concepts = np.array(data)[:,:-1]
concepts

target = np.array(data)[:,-1]
target

def train(concept, target):

  for i, val in enumerate(target):
    if(val.lower() == "yes"):
      specific_h = concept[i].copy()
      break

  for i, val in enumerate(concept):
    if(target[i].lower() == "yes"):
      for j in range(len(specific_h)):
        if(val[j] != specific_h[j]):
          specific_h[j] = "?"
        else:
          pass

  return specific_h

train(concepts, target)